import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import vm from 'node:vm';
const base=new URL('../extension/',import.meta.url);
const context=vm.createContext({});
vm.runInContext(await readFile(new URL('shared.js',base),'utf8'),context);
const P=context.SubmetaPreset;
assert.equal(P.normalize(null).enabled,false);
for(const rate of [NaN,Infinity,-1,0,1.1,'1.25',3])assert.equal(P.normalize({rate}).rate,1);
assert.equal(P.normalize({rate:1.25}).rate,1.25);
assert.equal(P.normalize({captions:'invalid'}).captions,'leave');
assert.equal(P.chooseLabel('ko',['English','Off']),null,'Do not substitute English for unavailable Korean');
assert.equal(P.chooseLabel('ko',['한국어','Off']),'한국어');
assert.equal(P.chooseLabel('en-US',['English','Off']),'English');
assert.equal(P.chooseLabel('Off',['한국어','Off']),'Off');
assert.equal(P.normalize({language:'<script>'}).language,'ko');
const b=P.budget();assert.ok(b.take(0));assert.ok(b.take(1));assert.ok(b.take(2));assert.equal(b.take(3),false);assert.ok(b.take(10000));
let listener;const sent=[];
const bg=vm.createContext({URL,browser:{runtime:{onMessage:{addListener:fn=>listener=fn}},tabs:{sendMessage:async(...args)=>{sent.push(args);return {ok:true};}}}});
vm.runInContext(await readFile(new URL('background.js',base),'utf8'),bg);
await listener({app:'submeta-preset',type:'relay',frameId:3},{tab:{id:7},frameId:0,url:'https://evil.example/'});
assert.equal(sent.length,0);
await listener({app:'submeta-preset',type:'relay',frameId:0},{tab:{id:7},frameId:0,url:'https://submeta.io/'});
assert.equal(sent.length,0);
await listener({app:'submeta-preset',type:'relay',frameId:3,token:'test'},{tab:{id:7},frameId:0,url:'https://submeta.io/'});
assert.equal(sent.length,1);assert.equal(sent[0][0],7);assert.equal(sent[0][2].frameId,3);
await listener({app:'submeta-preset',type:'status',token:'test'},{tab:{id:7},frameId:3,url:'https://iframe.cloudflarestream.com/redacted'});
assert.equal(sent.length,2);assert.equal(sent[1][2].frameId,0);assert.equal(sent[1][1].frameId,3);
const manifest=JSON.parse(await readFile(new URL('manifest.json',base),'utf8'));
assert.deepEqual(manifest.permissions,['storage']);
for(const file of new Set([...manifest.background.scripts,...manifest.content_scripts.flatMap(s=>s.js)]))new vm.Script(await readFile(new URL(file,base),'utf8'),{filename:file});
export const result='Passed: settings validation, unavailable-language policy, conflict budget, origin/frame routing, manifest and script syntax.';
