import {test} from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
import {webcrypto} from 'node:crypto';
const source=name=>readFileSync(new URL('../extension/gif/'+name,import.meta.url),'utf8');
const encoded=Uint8Array.from(Buffer.from('R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7','base64'));
async function settle(){for(let i=0;i<20;i++)await new Promise(resolve=>setImmediate(resolve));}
async function waitForResult(h){
  const deadline=Date.now()+5000;
  while(!(h.state.busy==='idle'&&h.state.previewURL)&&Date.now()<deadline)await new Promise(resolve=>setTimeout(resolve,10));
  assert.equal(h.state.busy,'idle');assert.ok(h.state.previewURL,'GIF generation should finish');
}
function setup({native=true,capture}={}) {
  const events={},updates=[],saves=[],revoked=[];let actions,onMessage,ui={},saveResponse={status:'complete'},folderResponse={status:'unselected'},encoderDisposed=0;
  const video={duration:285,currentTime:30,videoWidth:480,videoHeight:270,readyState:4,currentSrc:'fixture-existing-media'};
  const node=()=>({style:{},setAttribute(){},removeAttribute(){},addEventListener(){},attachShadow(){return{};},append(){}});
  class TestURL extends URL {static createObjectURL(){return 'blob:fixture-preview';}static revokeObjectURL(value){revoked.push(value);}}
  const context=vm.createContext({URL:TestURL,AbortController,Blob,Uint8Array,crypto:webcrypto,performance,console,
    window:{parent:{},addEventListener(type,listener){events[type]=listener;}},
    document:{referrer:'https://submeta.io/course',getElementById(){return null;},createElement:node,documentElement:node(),querySelector:()=>video,addEventListener(){},removeEventListener(){}},
    MutationObserver:class{observe(){}disconnect(){}},
    browser:{runtime:{getManifest:()=>({version:'0.4.1'}),sendMessage:async()=>({}),onMessage:{addListener(listener){onMessage=listener;}}}},
    SubmetaUI:{gifHostCSS:'',mountGifEditor(_root,options){actions=options.actions;return {update(next){ui=structuredClone(next);updates.push(ui);},trapFocus(){},focusClose(){},destroy(){}};}},
  });
  vm.runInContext(source('config.js'),context);
  Object.assign(context.SubmetaGif,{
    timeline(){},folder:async()=>native?folderResponse:{error:'native-host-unavailable'},pasteInstruction:async()=>'⌘V로 붙여넣으세요.',
    createEncoder:async()=>({frame:async()=>{},finish:async()=>({buffer:encoded.buffer,metrics:{}}),dispose(){encoderDisposed++;}}),
    capture:capture|| (async()=>({report:{restoration:'restored'}})),
    save:async(result,options)=>{saves.push({result,options});return options.destination==='clipboard'?{status:'copied'}:saveResponse;},
  });
  vm.runInContext(source('panel.js'),context);
  return {get actions(){return actions;},get state(){return ui;},message:value=>onMessage(value),updates,saves,revoked,video,events,get encoderDisposed(){return encoderDisposed;},set saveResponse(value){saveResponse=value;},set folderResponse(value){folderResponse=value;}};
}
test('GIF opening selects the current playback position and next five seconds every time',async()=>{
  const h=setup();await settle();
  h.video.currentTime=72.34;await h.message({type:'gif:ui-open'});
  assert.equal(h.state.start,'1:12.3');assert.equal(h.state.end,'1:17.3');
  h.actions.changeTime('start','0:10');h.actions.changeTime('end','0:15');
  await h.message({type:'gif:ui-close'});h.video.currentTime=100;
  await h.message({type:'gif:ui-open'});
  assert.equal(h.state.start,'1:40');assert.equal(h.state.end,'1:45');
  h.video.currentTime=283;await h.message({type:'gif:ui-open'});
  assert.equal(h.state.start,'4:43');assert.equal(h.state.end,'4:45');assert.equal(h.state.timeError,'');
  h.video.currentTime=284.5;await h.message({type:'gif:ui-open'});
  assert.equal(h.state.start,'4:44.5');assert.equal(h.state.end,'4:45');assert.ok(h.state.timeError);
});
test('GIF reopening resets the range while cancelled generation is still settling',async()=>{
  let finishCapture;
  const h=setup({capture:()=>new Promise(resolve=>{finishCapture=resolve;})});
  await settle();h.actions.generate();await settle();
  assert.equal(h.state.busy,'generating');
  await h.message({type:'gif:ui-close'});h.video.currentTime=80;
  await h.message({type:'gif:ui-open'});
  assert.equal(h.state.start,'1:20');assert.equal(h.state.end,'1:25');
  finishCapture({error:'cancelled',report:{restoration:'restored'}});await settle();
  assert.equal(h.state.busy,'idle');assert.equal(h.state.start,'1:20');assert.equal(h.state.end,'1:25');
});
test('GIF controller retains generated bytes across save failure and retry',async()=>{
  const h=setup();await settle();h.actions.generate();await waitForResult(h);
  assert.equal(h.state.busy,'idle');assert.equal(h.state.previewURL,'blob:fixture-preview');
  assert.equal(h.encoderDisposed,1);assert.equal(h.saves[0].options.destination,'clipboard');
  assert.ok(h.updates.some(state=>state.busy==='copying'));
  const result=h.saves[0].result;
  h.saveResponse={error:'file-no-space'};h.actions.save('remembered-folder');await settle();
  assert.equal(h.state.tone,'error');assert.equal(h.state.previewURL,result.url);
  h.saveResponse={status:'complete'};h.actions.save('browser');await settle();
  assert.equal(h.saves.at(-1).result,result);assert.equal(h.state.tone,'success');
  assert.equal(h.saves.at(-1).options.destination,'browser');
  h.events.pagehide();assert.deepEqual(h.revoked,[result.url]);
});
test('GIF cancellation aborts capture, retains times and disposes encoder',async()=>{
  let aborted=false;
  const h=setup({capture:({controller})=>new Promise(resolve=>controller.signal.addEventListener('abort',()=>{aborted=true;resolve({error:'cancelled',report:{restoration:'restored'}});} ))});
  await settle();h.actions.changeTime('start','0:40');h.actions.changeTime('end','0:45');h.actions.generate();await settle();
  assert.equal(h.state.busy,'generating');h.actions.cancel();await settle();
  assert.equal(aborted,true);assert.equal(h.state.busy,'idle');assert.equal(h.state.start,'0:40');assert.equal(h.state.end,'0:45');assert.match(h.state.status,/취소/);assert.equal(h.encoderDisposed,1);assert.equal(h.saves.length,0);
});
test('GIF input validation and unavailable helper keep browser save available',async()=>{
  const h=setup({native:false});await settle();assert.equal(h.state.nativeAvailable,false);
  h.actions.changeTime('start','0:99');assert.equal(h.state.invalid.start,true);assert.ok(h.state.timeError);
  h.actions.changeTime('start','0:30',true);assert.equal(h.state.timeError,'');
  h.actions.generate();await waitForResult(h);assert.equal(h.saves.length,0);assert.equal(h.state.previewURL,'blob:fixture-preview');
  h.actions.save('browser');await settle();assert.equal(h.saves.length,1);assert.equal(h.saves[0].options.destination,'browser');
});
