import {build} from 'esbuild';
import {readFileSync, writeFileSync} from 'node:fs';
const shared = {bundle:true, format:'iife', platform:'browser', target:['chrome102','firefox128'], jsx:'automatic', minify:true, legalComments:'inline', define:{'process.env.NODE_ENV':'"production"'}, write:false, charset:'utf8'};
const runtime = await build({...shared, entryPoints:['ui/runtime.ts']});
const buildApp = entry => build({...shared, entryPoints:[entry], plugins:[{
  name:'extension-local-react-runtime', setup(build) {
    build.onResolve({filter:/^react(?:\/jsx-runtime|-dom(?:\/client)?)?$/}, args => ({path:args.path,namespace:'runtime'}));
    build.onLoad({filter:/.*/,namespace:'runtime'}, args => ({contents:{
      'react':'export const {useLayoutEffect,useState,useRef,useId} = globalThis.SubmetaReactRuntime.React;',
      'react/jsx-runtime':'export const {jsx,jsxs,Fragment} = globalThis.SubmetaReactRuntime.JSX;',
      'react-dom/client':'export const {createRoot} = globalThis.SubmetaReactRuntime;',
      'react-dom':'export const {flushSync,createPortal} = globalThis.SubmetaReactRuntime;',
    }[args.path]}));
  },
}]});
const app = await buildApp('ui/mount.tsx');
const gif = await buildApp('ui/gif-mount.tsx');
const header = '// Generated by npm run ui:build. Edit ui/ sources, not this bundle.\n';
const outputs = {
  'extension/ui/react-runtime.js':header + runtime.outputFiles[0].text,
  'extension/ui/playback-settings.js':header + app.outputFiles[0].text,
  'extension/ui/gif-editor.js':header + gif.outputFiles[0].text,
  'extension/ui/THIRD_PARTY_LICENSES.txt':['react','react-dom','scheduler'].map(name => `${name}\n${readFileSync(`node_modules/${name}/LICENSE`,'utf8')}`).join('\n\n'),
};
for (const [file, content] of Object.entries(outputs)) {
  if (process.argv.includes('--check')) {
    if (readFileSync(file,'utf8') !== content) throw new Error(`${file} is stale. Run npm run ui:build`);
  } else writeFileSync(file,content);
}
console.log(`React UI ${process.argv.includes('--check') ? 'verified' : 'built'}: runtime ${Buffer.byteLength(outputs['extension/ui/react-runtime.js'])} bytes, application ${Buffer.byteLength(outputs['extension/ui/playback-settings.js'])} bytes.`);
