import {readFileSync, writeFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';

export function compile(document) {
  const {tokens, themes} = document;
  if (!tokens || !themes?.dark || !themes?.light) throw new Error('Tokens and dark/light themes are required');
  const resolved = new Map();
  function resolve(name, chain = []) {
    if (chain.includes(name)) throw new Error(`Token cycle: ${[...chain, name].join(' → ')}`);
    if (resolved.has(name)) return resolved.get(name);
    const token = tokens[name];
    if (!token) throw new Error(`Missing token: ${name}`);
    if (!/^[a-z][a-zA-Z0-9]*(\.[a-zA-Z0-9]+)+$/.test(name)) throw new Error(`Invalid token name: ${name}`);
    const ref = typeof token.value === 'string' && token.value.match(/^\{([^}]+)\}$/);
    if (ref && tokens[ref[1]]?.type !== token.type) throw new Error(`Missing reference or type mismatch: ${name} → ${ref[1]}`);
    const value = ref ? resolve(ref[1], [...chain, name]) : token.value;
    const valid = {color: v => /^#[0-9a-f]{6}$/i.test(v), dimension: v => /^\d+(\.\d+)?px$/.test(v), font: v => v === 'inherit', number: v => typeof v === 'number' && Number.isFinite(v) && v >= 0};
    if (!valid[token.type]?.(value)) throw new Error(`Invalid ${token.type}: ${name} = ${value}`);
    resolved.set(name, value); return value;
  }
  const variable = name => '--sm-' + name.replaceAll('.', '-').replace(/[A-Z]/g, c => '-' + c.toLowerCase());
  const names = Object.keys(tokens).sort();
  names.forEach(name => resolve(name));
  const declarations = values => Object.entries(values).map(([name, value]) => `${variable(name)}:${value}`).join(';');
  let css = `:host,:root,.sm-theme{${declarations(Object.fromEntries(resolved))}}`;
  for (const [theme, overrides] of Object.entries(themes)) {
    if (!['dark', 'light'].includes(theme)) throw new Error(`Unknown theme: ${theme}`);
    for (const [name, value] of Object.entries(overrides)) {
      if (tokens[name]?.type !== 'color' || !/^#[0-9a-f]{6}$/i.test(value)) throw new Error(`Invalid theme override: ${theme}.${name}`);
    }
    css += `\n:host([data-theme="${theme}"]),:root[data-theme="${theme}"],.sm-theme[data-theme="${theme}"]{${declarations(overrides)}}`;
  }
  const values = Object.fromEntries(resolved);
  return {css, values, js: `// Generated by scripts/design/tokens.mjs. Edit design/tokens.json.\n(() => {\n  const UI = globalThis.SubmetaUI ||= {};\n  UI.tokenCSS = ${JSON.stringify(css)};\n  UI.tokens = Object.freeze(${JSON.stringify(values)});\n})();\n`};
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const source = new URL('../../design/tokens.json', import.meta.url);
  const target = new URL('../../extension/ui/tokens.js', import.meta.url);
  const {js} = compile(JSON.parse(readFileSync(source, 'utf8')));
  if (process.argv.includes('--check')) {
    if (readFileSync(target, 'utf8') !== js) throw new Error('Generated tokens are stale. Run npm run design:generate');
    console.log('Token references, types, themes and generated output verified.');
  } else { writeFileSync(target, js); console.log('Generated extension/ui/tokens.js'); }
}
